- name: Configure Repositories on all servers
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- hosts: frontends
  become: yes
  roles:
    - lb-tier

- hosts: apps
  become: yes
  roles:
    - app-tier 

- hosts: appdbs
  become: yes
  roles:
    - db-tier

