---
# handlers file for good-ansible/roles/app-tier

- name: restart_tomcat
  service:
    name: tomcat
    state: restarted

- name: restart_firewalld
  service: 
    name: firewalld 
    state: restarted

