---
# tasks file for good-ansible/roles/app-tier

# Packages need to install - tomcat 
# Enable tomcat at boot
# create default web directory
# copy index.html
# restart tomcat service


- name: Install {{ tom_pkg }}
  yum: 
    name: "{{ tom_pkg }}"
    state: latest

- name: enable tomcat at boot
  service:
    name: "{{ tom_srv }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tom_web_root }}"
    state: directory

- name: copy index.html to tomcat web root directory
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html 
    mode: 0644
  notify: restart_tomcat

- name: Install Firewalld
  yum:
   name: firewalld
   state: latest

- name: Start firewalld service
  service:
   name: firewalld
   state: started
   enabled: true

- name: insert firewalld rule for tomcat http port
  firewalld: port={{ http_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: insert firewalld rule for tomcat https port
  firewalld: port={{ https_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

#- name: wait for tomcat to start
#  wait_for: port={{http_port}}
  notify: restart_firewalld

#- name: Open http port
#  firewalld:
#   service: http
#   state: enabled
#   immediate: true
#   permanent: true
#  notify: restart_firewalld

#- name: restart tomcat
#  service: 
#    name: "{{ tom_srv }}"
#    state: restarted
